USE QLVT
-- 1,
SELECT *
FROM NHACC
-- 2,
SELECT TenNCC, DienThoai
FROM NhaCC
WHERE DiaChi LIKE '%HCM'
-- 3,
SELECT *
FROM DonDH
WHERE MaNCC='C03' OR MaNCC='C05'
-- 4,
SELECT MaVT
FROM CTDonDH
WHERE SLDat>=10
-- 5,
SELECT TenVT
FROM VatTu
WHERE DvTinh LIKE N'Cái'
ORDER BY PhanTram
-- 6,
SELECT SoDH
FROM DonDH
WHERE MONTH(NgayDH)=3 AND YEAR(NgayDH)=2015
-- 7,
SELECT SoDH
FROM DonDH
WHERE MONTH(NgayDH)=2
-- 8,
SELECT SoPN
FROM PNhap
WHERE SoDH IN ('D001', 'D002', 'D005')
-- 9,
SELECT MaVT
FROM CTPNhap
WHERE DgNhap BETWEEN 3000000 AND 4000000
-- 10,
SELECT SoPX, NgayXuat
FROM PXuat
WHERE TenKH LIKE '%Nhi'
-- 11,
SELECT SoPX
FROM PXuat
WHERE NgayXuat BETWEEN '2002/01/20' AND '2002/01/31'
-- 12,
SELECT COUNT(SoPX) AS SLPXuat
FROM PXuat
-- 13,
SELECT MaVT
FROM CTPXuat
WHERE DgXuat>=3000000
-- 14,
SELECT MaVT, DgXuat
FROM CTPXuat
WHERE SLXuat>=2
-- 15,
SELECT TenNCC
FROM NhaCC
WHERE TenNCC LIKE 'T%'
-- 16,
SELECT *
FROM NhaCC
WHERE DienThoai LIKE N'Chưa có'
-- 17,
SELECT COUNT(SoPN) AS SLPNhap
FROM PNhap
-- 18,
SELECT AVG(DgXuat) AS DgXuatTB
FROM CTPXuat
-- 19,
SELECT MAX(DgXuat) AS DgXuatLN
FROM CTPXuat
WHERE MaVT LIKE 'DD01'
-- 20,
SELECT MIN(DgXuat) AS DgXuatNN
FROM CTPXuat
WHERE SoPX LIKE 'X003'
-- 21,
SELECT COUNT(TenVT) AS SLTivi
FROM VatTu
WHERE TenVT LIKE 'Tivi%'
-- 22,
SELECT SUM(SLDat) AS SLDatTivi
FROM CTDonDH
WHERE MaVT LIKE 'TV%'
-- 23,
SELECT DISTINCT MaNCC
FROM NhaCC
-- 24,
SELECT DISTINCT COUNT(MaNCC) AS SLNhaCC
FROM NhaCC
-- 25,
SELECT COUNT(SoPN) AS SoPNDD
FROM CTPNhap
WHERE MaVT LIKE 'DD%'
-- 26,
SELECT COUNT(MaVT) AS SLVTTonKho
FROM TonKho
WHERE NamThang LIKE '____02' AND NamThang LIKE '2002__'
-- 27,
SELECT TOP 3
    *
FROM CTPNhap
ORDER BY DgNhap
-- (?) 28,
SELECT SUM(SLNhap) AS SLNhap, SUM(SLXuat) AS SLXuat
FROM CTPNhap AS N, CTPXuat AS X
WHERE N.MaVT='VD02' AND X.MaVT='VD02'
-- 29,
SELECT MaVT, NamThang, SLCuoi
FROM TonKho
ORDER BY SLCuoi, TongSLX DESC
-- 30,
SELECT COUNT(SoDH) AS SLDH
FROM DonDH
WHERE MONTH(NgayDH)=02 AND YEAR(NgayDH)=2002
-- 31,
SELECT AVG(SLDat) AS SLTB
FROM CTDonDH
-- 32,
SELECT TOP 5
    *
FROM TonKho
ORDER BY SLCuoi DESC
-- 33,
SELECT MaVT, DgNhap,
    CASE
        WHEN DgNhap<2000000 THEN N'RẺ'
        WHEN DgNhap<=3000000 THEN N'TRUNG BÌNH'
        ELSE N'ĐẮT' 
    END AS DanhGia
FROM CTPNhap
-- 34,
SELECT DATEDIFF(YY, NgayXuat, GETDATE()) AS N'Số năm đã qua'
FROM PXuat
WHERE TenKH=N'Nguyễn Tuấn Tú'
-- 35,
SELECT MaVT
FROM TonKho
WHERE TongSLN>5 AND TongSLX>5